[item]
guid = 1EUuEFeshv8
title = "91yr old Giannina makes a Ligurian cheesy rice pie! | Pasta Grannies"
description = "Discover a savoury rice pie while listening to some of Giannina's life story. This 'torta di riso alla Genovese' is popular in Genova area of Liguria and cooks all have their own tweaks (some add nutmeg for example). \n250 ml milk\n180g arborio rice\n50ml olive oil, salt, \n300g in total of fresh cheese, in this case 250g of Prescinsêua and 25g of Campagnolo, 20g of Parmigiano. Try a mix of yoghurt with live cultures with cottage or feta cheese for a soured flavour instead of these local cheeses. \nfor the dough\n300g 00 flour\n50ml olive oil\nSalt\nWarm water, as needed."
author = Pasta Grannies
source = https://www.youtube.com/channel/UCedsqpl7jaIb8BiaUFuC9KQ
link = https://www.youtube.com/watch?v=1EUuEFeshv8
category = "Film & Animation"
pubdate = Fri, 03 Jun 2022 00:00:00 -0000
enclosure = 1EUuEFeshv8.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/1EUuEFeshv8/hqdefault.jpg

