[item]
guid = brSIdnhAON0
title = "Enjoy 87yr old Ottavia and her potato-filled culurgiones! | Pasta Grannies"
description = "Culurgiones are beautiful wheat-ear shaped ravioli from Sardinia.Every village in the Ogliastra area has its own version and Ottavia shares hers from Tertanía, south west Sardinia. Enjoy both her pasta and her weaving! \nPasta dough: 300g semola/durum wheat flour, 120ml water, 30ml olive oil\nFilling: 500g potatoes, 100g fresh goats curd, 25g pecorino, 1 tablespoon dried mint, pinch of salt, 1/2 garlic clove, a little flour if necessary, 100ml olive oil fried with 1 garlic clove.\nDress with tomato sauce and grated pecorino cheese"
author = Pasta Grannies
source = https://www.youtube.com/channel/UCedsqpl7jaIb8BiaUFuC9KQ
link = https://www.youtube.com/watch?v=brSIdnhAON0
category = "Film & Animation"
pubdate = Fri, 01 Jul 2022 00:00:00 -0000
enclosure = brSIdnhAON0.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/brSIdnhAON0/maxresdefault.webp

