[item]
guid = ewpGWbWF00o
title = "Enjoy Ave's anolini in brodo, flavoursome filled pasta from Parma | Pasta Grannies"
description = "Every family in the Parma area has their own recipe for anolini, and this is Ave's.\n For the pasta: 300g 00 flour, 3 eggs\nFor the filling:  250g pork loin/shoulder and 400g slice of beef shin/shank\n1 shallot, 4 cloves, 2 garlic cloves, 1-5cm shard of cinnamon, 200ml red wine. Simmer this until very tender, 14 hours may not be necessary. Remove the meat from the bone, mince it. Keep the juices, you will need around 400ml depending on how dry your breadcrumbs are. \n200g dry fine breadcrumbs, add enough stock/juices to moisten properly.\nmix in 100g each of 30 month and 36 month Parmigiano (or 200g of one)\n1 egg, nutmeg. Squish breadcrumbs and minced meat, cheese, nutmeg and egg together\nFor the stock: 1x 1.6kg whole chicken (stuffing these days is optional, but depending on the size of the chicken cavity: 300g fresh breadcrumbs, 200g grated Parmigiano, 2 tablespoons of chiffonade fresh spinach) 500g beef shin, one onion, 4 cloves, carrot, celery and bay leaf. Cover with water and simmer for at least 2 hours. Strain, the meat is sliced up and served as a main course, the stock is used for the aniline. \nThe special stamp creates no-frill pasta so the anolini look like buttons. It will taste the same if you have to use an ordinary ravioli stamp and seal the edges."
author = Pasta Grannies
source = https://www.youtube.com/channel/UCedsqpl7jaIb8BiaUFuC9KQ
link = https://www.youtube.com/watch?v=ewpGWbWF00o
category = "Film & Animation"
pubdate = Fri, 08 Jul 2022 00:00:00 -0000
enclosure = ewpGWbWF00o.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/ewpGWbWF00o/maxresdefault.jpg

