[item]
guid = HE2oedAwQTQ
title = "Discover a tuna with basil pesto pasta from Sardinia! | Pasta Grannies"
description = "This is called Pasticcio alla Carlofortina, it's from Sardinia, but also has its roots in Liguria. We went to Isola San Pietro to find out more about this recipe. Carolina shares her recipe. \nFor the pasta dough: 500g semola rimacinata (semolina flour) 250ml water, a pinch of salt ( or a mixture of bought pasta)\nFor the ragu: 500g fresh or tinned tuna, 500ml passata, 1 onion, 4 basil leaves, one glass white wine.\nfor the pesto: 1 garlic clove, 5 basil leaves, 3 tablespoons of extra virgin olive oil. 2 tablespoons of Italian pine nuts."
author = Pasta Grannies
source = https://www.youtube.com/channel/UCedsqpl7jaIb8BiaUFuC9KQ
link = https://www.youtube.com/watch?v=HE2oedAwQTQ
category = "Film & Animation"
pubdate = Fri, 24 Jun 2022 00:00:00 -0000
enclosure = HE2oedAwQTQ.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/HE2oedAwQTQ/hqdefault.jpg

