[item]
guid = hwyPszOBNDE
title = "Francesca makes Sinatra's granddad favourite sausage bread roll | Pasta Grannies"
description = "These stuffed bread rolls are called nfriulate and they are the Sicilian equivalent to Cornish pasties. They are a speciality of Lecara Friddi which is where Frank Sinatra's grandparents came from and the townsfolk are very proud of both. Here Francesca shares her recipe for what was Sinatra's grandfather Francesco's favourite meal. \n\nFor the filling:\n500g fresh chard or spinach\n500g fresh Italian fennel flavoured sausages (add a teaspoon of crushed fennel seeds if your sausages are plain)\n1 onion, 3 large potatoes\nolive oil, salt, black pepper\n\nbread dough: use your own recipe. Francesca used 500g semola rimacinata (though strong bread flour will also be fine), 1/2 cube of fresh yeast, 10g sugar, 5g salt, around 300ml of water."
author = Pasta Grannies
source = https://www.youtube.com/channel/UCedsqpl7jaIb8BiaUFuC9KQ
link = https://www.youtube.com/watch?v=hwyPszOBNDE
category = "Film & Animation"
pubdate = Fri, 17 Jun 2022 00:00:00 -0000
enclosure = hwyPszOBNDE.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/hwyPszOBNDE/hqdefault.jpg

