[item]
guid = U2g5b2yOuaY
title = "87yr old Maria makes cheese & parsley tortelloni! | Pasta Grannies"
description = "These tortelloni are lovely! Maria is one of our 'star' Pasta Grannies, who is happy to demonstrate her skills for visiting film crews. The tortelloni are filled with a mixture of cheeses, parsley and spinach and dressed with sage and just melted butter:\nfor the pasta: 400g 00 flour (or 80g semolina flour and 320g 00 flour) plus 4 eggs\nFor the filling: 200g each of young, but firm but not crumbly cheeses - Maria uses Castel San Pietro and Bucciatello - one egg, 400g 24 month Parmigiano, 2 tablespoons finely chopped parsley, 1 tablespoon finely chopped spinach. \nFor serving: a handful of fresh sage leaves, 50g of butter (or the amount you want)"
author = Pasta Grannies
source = https://www.youtube.com/channel/UCedsqpl7jaIb8BiaUFuC9KQ
link = https://www.youtube.com/watch?v=U2g5b2yOuaY
category = "Film & Animation"
pubdate = Fri, 15 Jul 2022 00:00:00 -0000
enclosure = U2g5b2yOuaY.mkv

[item "itunes"]
image = https://i.ytimg.com/vi/U2g5b2yOuaY/maxresdefault.jpg

