[item]
guid = VV7Y7TZG1Us
title = "Enjoy Rita, Giovanna and grandson Giulio make mushroom lasagna | Pasta Grannies"
description = "Cooking is a family activity for Rita and Giovanna and here they are making their favourite mushroom lasagna. \nFor the dough: 300g 00 flour, 3 eggs\nFor the béchamel: 1 litre semi skimmed milk, 80g each of butter and flour, plenty of nutmeg\nFor the mushrooms: a 750g mixture, including porcini if you can, 2 garlic cloves, 1/2 a glass of white wine, olive oil (not too much), salt\nTo assemble: 250g mozzarella, 50g Parmigiano or similar."
author = Pasta Grannies
source = https://www.youtube.com/channel/UCedsqpl7jaIb8BiaUFuC9KQ
link = https://www.youtube.com/watch?v=VV7Y7TZG1Us
category = "Film & Animation"
pubdate = Fri, 10 Jun 2022 00:00:00 -0000
enclosure = VV7Y7TZG1Us.mkv

[item "itunes"]
image = https://i.ytimg.com/vi_webp/VV7Y7TZG1Us/maxresdefault.webp

